export const TOGGLE_LIKED_VIDEO = "TOGGLE_LIKED_VIDEO";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
